export default defineEventHandler(async (event) => {
  return [
    {
      id: 0,
      name: "Redmi 10 Power (Power Black, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81eM15lVcJL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Power-Black-128GB-Storage/dp/B09Y64H8VS/ref=sr_1_4?qid=1679133649&s=electronics&sr=1-4",
      ratings: 4,
      no_of_ratings: 965,
      discount_price: "₹10,999",
      actual_price: "₹18,999",
    },
    {
      id: 1,
      name: "OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71AvQd3VzqL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Nord-Lite-128GB-Storage/dp/B09WQYFLRX/ref=sr_1_5?qid=1679133649&s=electronics&sr=1-5",
      ratings: 4.3,
      no_of_ratings: "113,956",
      discount_price: "₹18,999",
      actual_price: "₹19,999",
    },
    {
      id: 2,
      name: "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51UhwaQXCpL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Oneplus-Bluetooth-Wireless-Earphones-Bombastic/dp/B09TVVGXWS/ref=sr_1_6?qid=1679133649&s=electronics&sr=1-6",
      ratings: 4.2,
      no_of_ratings: "90,304",
      discount_price: "₹1,999",
      actual_price: "₹2,299",
    },
    {
      id: 3,
      name: "Samsung Galaxy M33 5G (Mystique Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus | Travel Adapte...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81I3w4J6yjL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Samsung-Mystique-Storage-Purchased-Separately/dp/B09TWGDY4W/ref=sr_1_7?qid=1679133649&s=electronics&sr=1-7",
      ratings: 4.1,
      no_of_ratings: "24,863",
      discount_price: "₹15,999",
      actual_price: "₹24,999",
    },
    {
      id: 4,
      name: "OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Nord-Black-128GB-Storage/dp/B09WQY65HN/ref=sr_1_8?qid=1679133649&s=electronics&sr=1-8",
      ratings: 4.3,
      no_of_ratings: "113,956",
      discount_price: "₹18,999",
      actual_price: "₹19,999",
    },
    {
      id: 5,
      name: "Redmi 10 Power (Sporty Orange, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81OZGH4fZiL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Power-Sporty-Orange-Storage/dp/B09Y5WPXGW/ref=sr_1_9?qid=1679133649&s=electronics&sr=1-9",
      ratings: 4,
      no_of_ratings: 625,
      discount_price: "₹10,999",
      actual_price: "₹18,999",
    },
    {
      id: 6,
      name: "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with mic, 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Ga...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51HBom8xz7L._AC_UL800_.jpg",
      link: "https://www.amazon.in/Airdopes-141-Playtime-Resistance-Bluetooth/dp/B09N3ZNHTY/ref=sr_1_10?qid=1679133649&s=electronics&sr=1-10",
      ratings: 3.9,
      no_of_ratings: "172,347",
      discount_price: "₹1,299",
      actual_price: "₹3,995",
    },
    {
      id: 7,
      name: "Apple 20W USB-C Power Adapter (for iPhone, iPad & AirPods)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61vtLhO6fDL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Apple-USB-C-Adapter-iPhone-AirPods/dp/B08L5WWFCY/ref=sr_1_11?qid=1679133649&s=electronics&sr=1-11",
      ratings: 4.6,
      no_of_ratings: "61,748",
      discount_price: "₹1,589",
      actual_price: "₹1,900",
    },
    {
      id: 8,
      name: 'Fire-Boltt Ninja Call Pro Plus 1.83" Smart Watch with Bluetooth Calling, AI Voice Assistance, 100 Sports Modes IP67 Ratin...',
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61S9aVnRZDL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Fire-Boltt-Bluetooth-Calling-Assistance-Resolution/dp/B0BF57RN3K/ref=sr_1_12?qid=1679133649&s=electronics&sr=1-12",
      ratings: 4.3,
      no_of_ratings: "16,949",
      discount_price: "₹1,799",
      actual_price: "₹19,999",
    },
    {
      id: 9,
      name: "Samsung Galaxy M33 5G (Emerald Brown, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus | Travel Adapter...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81lnKynSaqL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Samsung-Emerald-Storage-Purchased-Separately/dp/B0B14MR9L1/ref=sr_1_15?qid=1679133649&s=electronics&sr=1-15",
      ratings: 4.1,
      no_of_ratings: "24,863",
      discount_price: "₹15,999",
      actual_price: "₹24,999",
    },
    {
      id: 10,
      name: "realme narzo 50A Prime (Flash Black, 4GB RAM+64GB Storage) Full High Definition+ Display |50MP AI Triple Camera| Charger I...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81IPrkMDqVL._AC_UL800_.jpg",
      link: "https://www.amazon.in/realme-Storage-Definition-Display-Included/dp/B0BG1PYJR4/ref=sr_1_16?qid=1679133649&s=electronics&sr=1-16",
      ratings: 4,
      no_of_ratings: "8,307",
      discount_price: "₹9,749",
      actual_price: "₹13,499",
    },
    {
      id: 11,
      name: "Redmi A1 (Light Blue, 2GB RAM, 32GB Storage) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Andro...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81UT07JsBqL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Storage-Segment-5000mAh-Battery/dp/B0BBN4DZBD/ref=sr_1_17?qid=1679133649&s=electronics&sr=1-17",
      ratings: 4,
      no_of_ratings: "11,100",
      discount_price: "₹5,899",
      actual_price: "₹8,999",
    },
    {
      id: 12,
      name: "OnePlus Nord CE 2 Lite 5G (Blue Tide, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71AvQd3VzqL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Nord-Lite-128GB-Storage/dp/B09X586PKC/ref=sr_1_18?qid=1679133649&s=electronics&sr=1-18",
      ratings: 4.3,
      no_of_ratings: "113,956",
      discount_price: "₹20,999",
      actual_price: "₹21,999",
    },
    {
      id: 13,
      name: "boAt Airdopes Atom 81 True Wireless in Ear Earbuds with Upto 50H Playtime, Quad Mics ENx Tech, 13MM Drivers, Beast Mode(50...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51NKpc-CnBL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Airdopes-Atom-81-Wireless/dp/B0BKG5PQ6T/ref=sr_1_19?qid=1679133649&s=electronics&sr=1-19",
      ratings: 3.8,
      no_of_ratings: "3,327",
      discount_price: "₹1,299",
      actual_price: "₹4,490",
    },
    {
      id: 14,
      name: "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming,...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51tFAbNRaPL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Airdopes-141-Bluetooth-Wireless-Playtime/dp/B09N3XMZ5F/ref=sr_1_20?qid=1679133649&s=electronics&sr=1-20",
      ratings: 3.9,
      no_of_ratings: "172,347",
      discount_price: "₹1,299",
      actual_price: "₹4,490",
    },
    {
      id: 15,
      name: "boAt BassHeads 100 in-Ear Wired Headphones with Mic (Black)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/719elVA3FvL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-BassHeads-100-Headphones-Black/dp/B071Z8M4KX/ref=sr_1_21?qid=1679133649&s=electronics&sr=1-21",
      ratings: 4.1,
      no_of_ratings: "375,110",
      discount_price: "₹399",
      actual_price: "₹999",
    },
    {
      id: 16,
      name: "boAt Rockerz 330 Bluetooth Wireless in Ear Earphones with mic, Upto 30 Hours Playtime, ASAP Charge, Signature Sound, Dual ...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/514sHd2+YyS._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Rockerz-330-Bluetooth-Assistant/dp/B092XRRZ6C/ref=sr_1_22?qid=1679133649&s=electronics&sr=1-22",
      ratings: 4.1,
      no_of_ratings: "114,951",
      discount_price: "₹1,099",
      actual_price: "₹3,990",
    },
    {
      id: 17,
      name: "Lapster 5-in-1 Multi-Function Laptop Cleaning Brush/Keyboard Cleaning kit/Gadget Cleaning kit Gap Duster Key-Cap Puller fo...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51+UotA4ExL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Lapster-Multi-Function-Cleaning-Keyboard-Earphones/dp/B0BBW16VH9/ref=sr_1_23?qid=1679133649&s=electronics&sr=1-23",
      ratings: 4.2,
      no_of_ratings: 765,
      discount_price: "₹97",
      actual_price: "₹999",
    },
    {
      id: 18,
      name: "boAt Wave Call Smart Watch, Smart Talk with Advanced Dedicated Bluetooth Calling Chip, 1.69 HD Display with 550 NITS & 70%...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/614AipEWSIL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Wave-Call-Dedicated-Multi-Sport/dp/B0B5B6PQCT/ref=sr_1_24?qid=1679133649&s=electronics&sr=1-24",
      ratings: 3.8,
      no_of_ratings: "23,231",
      discount_price: "₹1,999",
      actual_price: "₹7,990",
    },
    {
      id: 19,
      name: "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51RP1QMh-mL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Oneplus-Bluetooth-Wireless-Earphones-Bombastic/dp/B0B3MNYGTW/ref=sr_1_25?qid=1679133649&s=electronics&sr=1-25",
      ratings: 4.2,
      no_of_ratings: "90,304",
      discount_price: "₹1,999",
      actual_price: "₹2,299",
    },
    {
      id: 20,
      name: "boAt Airdopes 121v2 in-Ear True Wireless Earbuds with Upto 14 Hours Playback, 8MM Drivers, Battery Indicators, Lightweight...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/510+wjzq-vL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Airdopes-121v2-Bluetooth-Immersive-Assistant/dp/B08JQN8DGZ/ref=sr_1_26?qid=1679133649&s=electronics&sr=1-26",
      ratings: 3.8,
      no_of_ratings: "188,031",
      discount_price: "₹1,099",
      actual_price: "₹2,990",
    },
    {
      id: 21,
      name: "Redmi A1 (Black, 2GB RAM, 32GB Storage) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Android 12",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81BxHYjeA2L._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Storage-Segment-5000mAh-Battery/dp/B0BBN56J5H/ref=sr_1_27?qid=1679133649&s=electronics&sr=1-27",
      ratings: 4,
      no_of_ratings: "11,100",
      discount_price: "₹5,899",
      actual_price: "₹8,999",
    },
    {
      id: 22,
      name: "Redmi 10A (Charcoal Black, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | U...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71293gyogZL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Charcoal-Storage-Battery-Booster/dp/B09XB8GFBQ/ref=sr_1_28?qid=1679133649&s=electronics&sr=1-28",
      ratings: 4,
      no_of_ratings: "15,480",
      discount_price: "₹8,599",
      actual_price: "₹11,999",
    },
    {
      id: 23,
      name: "OnePlus 11R 5G (Galactic Silver, 16GB RAM, 256GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/613SAOPmLeL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Galactic-Silver-256GB-Storage/dp/B0BSNNYHY5/ref=sr_1_29?qid=1679133649&s=electronics&sr=1-29",
      ratings: 4.6,
      no_of_ratings: 338,
      discount_price: "",
      actual_price: "₹44,999",
    },
    {
      id: 24,
      name: "OnePlus Nord 2T 5G (Jade Fog, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61ahn9N38zL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Nord-Jade-128GB-Storage/dp/B0B3CPQ5PF/ref=sr_1_27?qid=1679133651&s=electronics&sr=1-27",
      ratings: 4.3,
      no_of_ratings: "21,232",
      discount_price: "",
      actual_price: "₹28,999",
    },
    {
      id: 25,
      name: "OnePlus Nord Buds True Wireless in Ear Earbuds with Mic, 12.4mm Titanium Drivers, Playback:Up to 30hr case, 4-Mic Design +...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/514NPRZ1AQL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Wireless-Earbuds-Titanium-Playback/dp/B09ZHPN8W5/ref=sr_1_28?qid=1679133651&s=electronics&sr=1-28",
      ratings: 4.2,
      no_of_ratings: "23,720",
      discount_price: "₹2,799",
      actual_price: "₹2,999",
    },
    {
      id: 26,
      name: "OnePlus Nord 2T 5G (Gray Shadow, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/617MPEZB5mL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Nord-Shadow-128GB-Storage/dp/B0B3CQBRB4/ref=sr_1_29?qid=1679133651&s=electronics&sr=1-29",
      ratings: 4.3,
      no_of_ratings: "21,232",
      discount_price: "",
      actual_price: "₹28,999",
    },
    {
      id: 27,
      name: "boAt Rockerz 255 Pro+ in-Ear Bluetooth Neckband with Upto 40 Hours Playback, ASAP Charge, IPX7, Dual Pairing, BT v5.0, wi...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51aBTOiXRlL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Rockerz-255-Pro-Earphones/dp/B08TV2P1N8/ref=sr_1_30?qid=1679133651&s=electronics&sr=1-30",
      ratings: 4.1,
      no_of_ratings: "148,827",
      discount_price: "₹1,499",
      actual_price: "₹3,990",
    },
    {
      id: 28,
      name: "boAt Rockerz 255 Pro+ in-Ear Bluetooth Neckband with Upto 40 Hours Playback, ASAP Charge, IPX7, Dual Pairing, BT v5.0, wi...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/515jdxLlmaL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Rockerz-255-Pro-Earphones/dp/B08TTXNZ4Y/ref=sr_1_31?qid=1679133651&s=electronics&sr=1-31",
      ratings: 4.1,
      no_of_ratings: "148,827",
      discount_price: "₹1,299",
      actual_price: "₹3,990",
    },
    {
      id: 29,
      name: 'Hammer Ace 3.0 Bluetooth Calling Smart Watch with Largest 1.85" IPS Display, Dual Mode, Spo2, Heart Rate, Strong Metallic ...',
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61jQim6YPnL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Hammer-Ace-3-0-Bluetooth-Rotating/dp/B0BV6FVKSP/ref=sr_1_32?qid=1679133651&s=electronics&sr=1-32",
      ratings: "Get",
      no_of_ratings: "FREE Delivery by Amazon",
      discount_price: "₹1,499",
      actual_price: "₹4,999",
    },
    {
      id: 30,
      name: "iQOO Z6 Lite 5G by vivo (Stellar Green, 6GB RAM, 128GB Storage) | World's First Snapdragon 4 Gen 1 | 120Hz Refresh Rate | ...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61VbKHdE0rL._AC_UL800_.jpg",
      link: "https://www.amazon.in/iQOO-Stellar-Snapdragon-Purchased-Separately/dp/B07WJV6P1R/ref=sr_1_33?qid=1679133651&s=electronics&sr=1-33",
      ratings: 4.1,
      no_of_ratings: "22,254",
      discount_price: "₹15,499",
      actual_price: "₹18,999",
    },
    {
      id: 31,
      name: "MI Power Bank 3i 20000mAh Lithium Polymer 18W Fast Power Delivery Charging | Input- Type C | Micro USB| Triple Output | Sa...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71lVwl3q-kL._AC_UL800_.jpg",
      link: "https://www.amazon.in/20000mAh-Sandstone-Triple-Charging-Delivery/dp/B08HV83HL3/ref=sr_1_34?qid=1679133651&s=electronics&sr=1-34",
      ratings: 4.3,
      no_of_ratings: "135,528",
      discount_price: "₹2,049",
      actual_price: "₹2,199",
    },
    {
      id: 32,
      name: "SanDisk Cruzer Blade 32GB USB Flash Drive",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61DjwgS4cbL._AC_UL800_.jpg",
      link: "https://www.amazon.in/SanDisk-Cruzer-Blade-Flash-Drive/dp/B005FYNT3G/ref=sr_1_35?qid=1679133651&s=electronics&sr=1-35",
      ratings: 4.3,
      no_of_ratings: "99,698",
      discount_price: "₹278",
      actual_price: "₹650",
    },
    {
      id: 33,
      name: "SanDisk Ultra® microSDXC™ UHS-I Card, 64GB, 140MB/s R, 10 Y Warranty, for Smartphones",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/7180ZAZmERL._AC_UL800_.jpg",
      link: "https://www.amazon.in/SanDisk-Ultra%C2%AE-microSDXCTM-Warranty-Smartphones/dp/B0BDRVFDKP/ref=sr_1_36?qid=1679133651&s=electronics&sr=1-36",
      ratings: 4.4,
      no_of_ratings: "71,768",
      discount_price: "₹488",
      actual_price: "₹1,000",
    },
    {
      id: 34,
      name: "boAt Airdopes 141 Pro True Wireless in Ear Earbuds with 45H Playtime, Quad Mics Enx Tech, 12mm Drivers, ASAP Charge, Beast...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/41TWloBD6XL._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Airdopes-141-Pro-Wireless/dp/B0B7J5ZTXD/ref=sr_1_37?qid=1679133651&s=electronics&sr=1-37",
      ratings: 3.9,
      no_of_ratings: "172,347",
      discount_price: "₹1,399",
      actual_price: "₹2,990",
    },
    {
      id: 35,
      name: "Redmi A1 (Light Green, 2GB RAM 32GB ROM) | Segment Best AI Dual Cam | 5000mAh Battery | Leather Texture Design | Android 12",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81UmTnrBDSL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Segment-5000mAh-Battery-Leather/dp/B0BBN3WF7V/ref=sr_1_38?qid=1679133651&s=electronics&sr=1-38",
      ratings: 4,
      no_of_ratings: "11,100",
      discount_price: "₹5,899",
      actual_price: "₹8,999",
    },
    {
      id: 36,
      name: "OnePlus 11R 5G (Galactic Silver, 8GB RAM, 128GB Storage)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/613SAOPmLeL._AC_UL800_.jpg",
      link: "https://www.amazon.in/OnePlus-Galactic-Silver-128GB-Storage/dp/B0BSNQ2KXF/ref=sr_1_39?qid=1679133651&s=electronics&sr=1-39",
      ratings: 4.6,
      no_of_ratings: 338,
      discount_price: "",
      actual_price: "₹39,999",
    },
    {
      id: 37,
      name: 'Fire-Boltt Phoenix Smart Watch with Bluetooth Calling 1.3",120+ Sports Modes, 240 * 240 PX High Res with SpO2, Heart Rate ...',
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61y2VVWcGBL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Fire-Boltt-Phoenix-Bluetooth-Calling-Monitoring/dp/B0B3RRWSF6/ref=sr_1_40?qid=1679133651&s=electronics&sr=1-40",
      ratings: 4.3,
      no_of_ratings: "43,302",
      discount_price: "₹1,699",
      actual_price: "₹2,199",
    },
    {
      id: 38,
      name: "Samsung 25W USB Travel Adapter for Cellular Phones - White",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/21uXmiH98wL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Samsung-25W-Travel-Adapter/dp/B08VFF6JQ8/ref=sr_1_41?qid=1679133651&s=electronics&sr=1-41",
      ratings: 4.4,
      no_of_ratings: "10,024",
      discount_price: "₹1,099",
      actual_price: "₹1,699",
    },
    {
      id: 39,
      name: "boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming,...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/516MceMiCdL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Airdopes-141-Bluetooth-Wireless-Playtime/dp/B09N3ZLB3T/ref=sr_1_42?qid=1679133651&s=electronics&sr=1-42",
      ratings: 3.9,
      no_of_ratings: "172,347",
      discount_price: "₹1,299",
      actual_price: "₹4,490",
    },
    {
      id: 40,
      name: "pTron Bassbuds Duo in Ear Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless, Stereo Audio, Touch Control TWS, with...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51ZT3aMrJIL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Bassbuds-Duo-Headphones-Water-Resistant-Assistance/dp/B09DD9SX9Z/ref=sr_1_43?qid=1679133651&s=electronics&sr=1-43",
      ratings: 3.5,
      no_of_ratings: "166,395",
      discount_price: "₹799",
      actual_price: "₹2,599",
    },
    {
      id: 41,
      name: "TAGG Verve Sense Smartwatch with 1.70'' Large Display, Real SPO2, and Real-Time Heart Rate Tracking, 7 Days Battery Backu...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51zv+mozGgL._AC_UL800_.jpg",
      link: "https://www.amazon.in/TAGG-Verve-Sense-Smartwatch-Waterproof/dp/B09Q4MRW85/ref=sr_1_44?qid=1679133651&s=electronics&sr=1-44",
      ratings: 3.7,
      no_of_ratings: "2,068",
      discount_price: "₹999",
      actual_price: "₹6,999",
    },
    {
      id: 42,
      name: "Portronics Toad 23 Wireless Optical Mouse with 2.4GHz, USB Nano Dongle, Optical Orientation, Click Wheel, Adjustable DPI(B...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/41KuRShR97L._AC_UL800_.jpg",
      link: "https://www.amazon.in/Portronics-Wireless-Optical-Orientation-Adjustable/dp/B0B296NTFV/ref=sr_1_45?qid=1679133651&s=electronics&sr=1-45",
      ratings: 4.1,
      no_of_ratings: "2,485",
      discount_price: "₹299",
      actual_price: "₹599",
    },
    {
      id: 43,
      name: "Samsung Galaxy M04 Light Green, 4GB RAM, 64GB Storage | Upto 8GB RAM with RAM Plus | MediaTek Helio P35 | 5000 mAh Battery",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/814ePfNubRL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Samsung-Galaxy-Storage-MediaTek-Battery/dp/B0BMGB2TPR/ref=sr_1_46?qid=1679133651&s=electronics&sr=1-46",
      ratings: 4,
      no_of_ratings: "1,754",
      discount_price: "₹8,499",
      actual_price: "₹11,999",
    },
    {
      id: 44,
      name: "ZEBRONICS Zeb-Bro in Ear Wired Earphones with Mic, 3.5mm Audio Jack, 10mm Drivers, Phone/Tablet Compatible(Black)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51D37uhFFBL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Zebronics-Zeb-Bro-Wired-Earphone/dp/B07T5DKR5D/ref=sr_1_47?qid=1679133651&s=electronics&sr=1-47",
      ratings: 3.5,
      no_of_ratings: "24,675",
      discount_price: "₹149",
      actual_price: "₹399",
    },
    {
      id: 45,
      name: "realme narzo 50A Prime (Flash Blue, 4GB RAM+128GB Storage) FHD+ Display | 50MP AI Triple Camera| Charger Included",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/81g0X076+WL._AC_UL800_.jpg",
      link: "https://www.amazon.in/realme-Storage-Display-Charger-Included/dp/B0BG1NWLY3/ref=sr_1_48?qid=1679133651&s=electronics&sr=1-48",
      ratings: 4,
      no_of_ratings: "8,307",
      discount_price: "₹10,499",
      actual_price: "₹14,499",
    },
    {
      id: 46,
      name: "boAt Bassheads 220 Wired in Ear Earphones(Black Indi)",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61iSV4o+X-L._AC_UL800_.jpg",
      link: "https://www.amazon.in/boAt-Bassheads-220-Wired-Earphones/dp/B0BRXY7FQB/ref=sr_1_49?qid=1679133651&s=electronics&sr=1-49",
      ratings: 4.1,
      no_of_ratings: "276,491",
      discount_price: "₹399",
      actual_price: "₹999",
    },
    {
      id: 47,
      name: "OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/514m1VhSUUL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Bluetooth-Wireless-Earphones-Bombastic-Launched/dp/B09TVV1TXL/ref=sr_1_50?qid=1679133651&s=electronics&sr=1-50",
      ratings: 4.2,
      no_of_ratings: "90,304",
      discount_price: "₹1,999",
      actual_price: "₹2,299",
    },
    {
      id: 48,
      name: "boAt Rockerz 450 Bluetooth On Ear Headphones with Mic, Upto 15 Hours Playback, 40MM Drivers, Padded Ear Cushions, Integrat...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/51xxA+6E+xL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Rockerz-450-Wireless-Bluetooth-Headphone/dp/B07PR1CL3S/ref=sr_1_51?qid=1679133652&s=electronics&sr=1-51",
      ratings: 4.1,
      no_of_ratings: "111,019",
      discount_price: "₹1,299",
      actual_price: "₹3,990",
    },
    {
      id: 49,
      name: "Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | Upto ...",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/71kVEmAMyEL._AC_UL800_.jpg",
      link: "https://www.amazon.in/Redmi-Storage-Battery-Finger-Booster/dp/B09XB7SRQ5/ref=sr_1_52?qid=1679133652&s=electronics&sr=1-52",
      ratings: 4,
      no_of_ratings: "15,480",
      discount_price: "₹8,599",
      actual_price: "₹11,999",
    },
    {
      id: 50,
      name: "JK Copier Paper - A4, 75 GSM, 1 Ream, 500 Sheets",
      main_category: "tv, audio & cameras",
      sub_category: "All Electronics",
      image: "https://m.media-amazon.com/images/I/61hhCaLLcuL._AC_UL800_.jpg",
      link: "https://www.amazon.in/JK-Copier-Paper-Sheets-Ream/dp/B00MVV81MK/ref=sr_1_53?qid=1679133652&s=electronics&sr=1-53",
      ratings: 4.3,
      no_of_ratings: "12,373",
      discount_price: "₹349",
      actual_price: "₹375",
    },
  ];
});
